### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tobytes'

### ISSUE THREAD

**Issue by AliothJ** [Mangio621/Mangio-RVC-Fork#150]
C:\Mangio-RVC-v23.7.0>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Found GPU NVIDIA GeForce GTX 1650 SUPER , force to fp32
Use Language: en_US
Running on local URL:  http://0.0.0.0:7897

To create a public link, set `share=True` in `launch()`.
loading weights/ayasev2_e229_s3206.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
loading rmvpe model
Traceback (most recent call last):
  File "C:\Mangio-RVC-v23.7.0\infer-web.py", line 316, in vc_single
    audio_opt = vc.pipeline(
  File "C:\Mangio-RVC-v23.7.0\vc_infer_pipeline.py", line 564, in pipeline
    self.vc(
  File "C:\Mangio-RVC-v23.7.0\vc_infer_pipeline.py", line 450, in vc
    (net_g.infer(feats, p_len, pitch, pitchf, sid)[0][0, 0])
  File "C:\Mangio-RVC-v23.7.0\lib\infer_pack\models.py", line 760, in infer
    o = self.dec(z * x_mask, nsff0, g=g)
  File "C:\Mangio-RVC-v23.7.0\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Mangio-RVC-v23.7.0\lib\infer_pack\models.py", line 511, in forward
    xs += self.resblocks[i * self.num_kernels + j](x)
  File "C:\Mangio-RVC-v23.7.0\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Mangio-RVC-v23.7.0\lib\infer_pack\modules.py", line 301, in forward
    xt = F.leaky_relu(x, LRELU_SLOPE)
  File "C:\Mangio-RVC-v23.7.0\runtime\lib\site-packages\torch\nn\functional.py", line 1632, in leaky_relu
    result = torch._C._nn.leaky_relu(input, negative_slope)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 178.00 MiB (GPU 0; 4.00 GiB total capacity; 2.40 GiB already allocated; 0 bytes free; 3.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Traceback (most recent call last):
  File "C:\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "C:\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

im having this issue. how do i resolve this?

**Comment by Leo7GoUp** [comment]
Hey Buddy,

i resolved this issue through using the default audio path. I just renamed the .mp3/.wav file for example,

C:/Users/XXX/Desktop/RVC/Mangio-RVC-v23.7.0/audios/XXX.wav

That worked for me :) 

Hopefully for you aswell,

Cheers out

**Comment by Leo7GoUp** [comment]
Ok, i checked it again and you have to put the "index" file into logs folder. That will resolve it

**Comment by AliothJ** [comment]
> Ok, i checked it again and you have to put the "index" file into logs folder. That will resolve it

Which index file is it? Thank you!

**Comment by jaystatio** [comment]
> Ok, i checked it again and you have to put the "index" file into logs folder. That will resolve it

Where do we find the index file are you talking about? Please help.

**Comment by jaystatio** [comment]
> Ok, i checked it again and you have to put the "index" file into logs folder. That will resolve it

Where do we find the index file you are talking about? Please help.

**Comment by Kevin201110219** [comment]
> Ok, i checked it again and you have to put the "index" file into logs folder. That will resolve it

bro your comment do not help anyone

**Comment by DrFisura** [comment]
> Ok, i checked it again and you have to put the "index" file into logs folder. That will resolve it

I copied the index file into the `logs` folder, and then explicitly told the route to the index file into the webui rather than let it detect automatically, and it worked. BUT, I guess it could have worked by putting the index file in just about any folder, and then indicating where it is in the path field in the webui.

(I copied and pasted the 'added' index file for this, not the 'trained' one. It was as simple as copying it from `logs/mute` into `logs`)

**Comment by student7545** [comment]
dude be a bit more helpful, explain what index file you are referring we are not mind readers thanks
