### ISSUE TITLE
CUDA is not available. Make sure you have an NVIDIA GPU and CUDA installed. But I have CUDA, why i'm getting this?

### ISSUE THREAD

**Issue by Juranik** [Mangio621/Mangio-RVC-Fork#177]
(venv) C:\Users\Administrator\Desktop\Mangio-RVC-Fork>python infer-web.py
No supported Nvidia GPU found, use CPU instead
CUDA is not available. Make sure you have an NVIDIA GPU and CUDA installed.
Use Language: en_US
Running on local URL:  http://0.0.0.0:7865
It is writing that I don't have cuda nvidia gpu, but I have cuda, and I installed it 11.8 n I have NVIDIA GPU, why Ima getting this? What should I do? Pls help me anyone!!

![286596833-1c24f1d1-2261-4212-a985-75cd887fa4d3](https://github.com/Mangio621/Mangio-RVC-Fork/assets/141658830/10b97fc1-2555-4a41-bd61-53bb61646080)

```
C:\Users\Administrator>nvidia-smi
Fri Dec  8 02:32:03 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 522.25       Driver Version: 522.25       CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P8    10W /  N/A |   1863MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      5668      C   ...thon\Python310\python.exe    N/A      |
+-----------------------------------------------------------------------------+
```

**Comment by taellinglin** [comment]
I am also getting this error

**Comment by taellinglin** [comment]
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

I did this, then also install ffmpy, and it's still not detecting my GPU

**Comment by taellinglin** [comment]
PS D:\MangioRVC> py .\infer-web.py --port 9999
No supported Nvidia GPU found, use CPU instead
CUDA is not available. Make sure you have an NVIDIA GPU and CUDA installed.
Use Language: ja_JP
Running on local URL:  http://127.0.0.1:9999
Running on public URL: https://17d
xxxxc769408c5f53.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)

**Comment by Juranik** [comment]
> PS D:\MangioRVC> py .\infer-web.py --port 9999 No supported Nvidia GPU found, use CPU instead CUDA is not available. Make sure you have an NVIDIA GPU and CUDA installed. Use Language: ja_JP Running on local URL: http://127.0.0.1:9999 Running on public URL: https://17d xxxxc769408c5f53.gradio.live
> 
> This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)

Hello, blud, I fixed this error, I'm just put this command, but first I activated venv in project, and I put this command, u should try the same: ```pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118```

Let me know, if it will solve ur problem, becuz I solved via this command, and also I'm downloaded old driver for my RTX3060, that supporting CUDA 11.8, and after I writed command which I indicated above.
